package com.example.randomnamesapp.utils

import com.example.randomnamesapp.R

object OriginStrings {
    val map = mapOf(
        "African" to R.string.origin_African,
        "Albanian" to R.string.origin_Albanian,
        "Spanish" to R.string.origin_Spanish,
        "Armenian" to R.string.origin_Armenian,
        "Azerbaijani" to R.string.origin_Azerbaijani,
        "Basque" to R.string.origin_Basque,
        "Belarusian" to R.string.origin_Belarusian,
        "Bengali" to R.string.origin_Bengali,
        "Bosnian" to R.string.origin_Bosnian,
        "Breton" to R.string.origin_Breton,
        "Bulgarian" to R.string.origin_Bulgarian,
        "Catalan" to R.string.origin_Catalan,
        "Chinese" to R.string.origin_Chinese,
        "Croatian" to R.string.origin_Croatian,
        "Czech" to R.string.origin_Czech,
        "Danish" to R.string.origin_Danish,
        "Dutch" to R.string.origin_Dutch,
        "English" to R.string.origin_English,
        "Estonian" to R.string.origin_Estonian,
        "Finnish" to R.string.origin_Finnish,
        "French" to R.string.origin_French,
        "Frisian" to R.string.origin_Frisian,
        "Galician" to R.string.origin_Galician,
        "Georgian" to R.string.origin_Georgian,
        "German" to R.string.origin_German,
        "Greek" to R.string.origin_Greek,
        "Hausa" to R.string.origin_Hausa,
        "Hawaiian" to R.string.origin_Hawaiian,
        "Hebrew" to R.string.origin_Hebrew,
        "Hungarian" to R.string.origin_Hungarian,
        "Icelandic" to R.string.origin_Icelandic,
        "Igbo" to R.string.origin_Igbo,
        "Indian" to R.string.origin_Indian,
        "Indonesian" to R.string.origin_Indonesian,
        "Irish" to R.string.origin_Irish,
        "Italian" to R.string.origin_Italian,
        "Japanese" to R.string.origin_Japanese,
        "Kazakh" to R.string.origin_Kazakh,
        "Khmer" to R.string.origin_Khmer,
        "Korean" to R.string.origin_Korean,
        "Latvian" to R.string.origin_Latvian,
        "Limburgish" to R.string.origin_Limburgish,
        "Lithuanian" to R.string.origin_Lithuanian,
        "Macedonian" to R.string.origin_Macedonian,
        "Malay" to R.string.origin_Malay,
        "Maori" to R.string.origin_Maori,
        "Polish" to R.string.origin_Polish,
        "Nepali" to R.string.origin_Nepali,
        "Norwegian" to R.string.origin_Norwegian,
        "Persian" to R.string.origin_Persian,
        "Romanian" to R.string.origin_Romanian,
        "Portuguese" to R.string.origin_Portuguese,
        "Russian" to R.string.origin_Russian,
        "Scottish" to R.string.origin_Scottish,
        "Serbian" to R.string.origin_Serbian,
        "Slovak" to R.string.origin_Slovak,
        "Slovene" to R.string.origin_Slovene,
        "Swahili" to R.string.origin_Swahili,
        "Swedish" to R.string.origin_Swedish,
        "Thai" to R.string.origin_Thai,
        "Turkish" to R.string.origin_Turkish,
        "Ukrainian" to R.string.origin_Ukrainian,
        "Urdu" to R.string.origin_Urdu,
        "Vietnamese" to R.string.origin_Vietnamese,
        "Welsh" to R.string.origin_Welsh,
        "Yoruba" to R.string.origin_Yoruba,
        "Zulu" to R.string.origin_Zulu,
        "Mythology" to R.string.origin_Mythology,
        "Pop" to R.string.origin_Pop,
        "History" to R.string.origin_History,
        "Carolingian Cycle" to R.string.origin_Carolingian_Cycle,
        "Astronomy" to R.string.origin_Astronomy,
        "Ancient" to R.string.origin_Ancient,
        "Esperanto" to R.string.origin_Esperanto,
        "Literature" to R.string.origin_Literature,
        "Fijian" to R.string.origin_Fijian,
        "Arthurian" to R.string.origin_Arthurian,
        "Biblical" to R.string.origin_Biblical
    )

    val mapGenders = mapOf(
        "Masculine" to R.string.maleStr,
        "Feminine" to R.string.femaleStr,
        "Either" to R.string.eitherStr
    )
}